config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resource :user

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!STANDARD!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  get 'faq' => 'pages#faq'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'termsandconditions' => 'pages#t_c_page'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'our-masterclasses' => 'pages#masterclasses'
  get 'personal-styling' => 'pages#personal_styling'
  get 'become_contributor' => 'pages#become_contributor'
  get 'personal-development' => 'pages#personal_development'
  get 'fitness-and-nutrition' => 'pages#fitness_and_nutrition'

  # resources :photos # TODO: REMOVE RESOURCE
  # resources :contents # TODO: REMOVE RESOURCE
  # resources :comments # TODO: REMOVE RESOURCE
  resources :posts
  resources :attachments
  resources :categories
  resources :contacts, only: %i[new create]
  resources :masterclasses

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!MEMBERS!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :members do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end

  namespace :contributors do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!ADMINS!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admins do
    root to: 'collections#index'
    resources :collections
    resources :masterclasses
    resources :posts
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!CK EDITOR!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  mount Ckeditor::Engine => '/ckeditor'

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!BILLING!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  scope '/subscriptions', :controller => :subscriptions do
    post :webhook_callback
  end

  resources :subscriptions do
    get :new_sub, on: :collection
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!# TODO:
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admin do
    resources :users
    # resources :contents
    # resources :documents
    # resources :events
    resources :masterclasses
    resources :posts

    resources :comments
    # resources :posts_contents
    resources :subscriptions
    resources :categories
    resources :serversettings
    # resources :videos
    root to: 'users#index'
  end
end

app/controllers/contributors/collections_controller.rb
module Contributors
  class CollectionsController < ::Contributors::NamespaceController
    before_action :set_collection
    before_action :set_users_collection
    before_action :set_stage
    def show; end

    private

    def set_collection
      @collection = Collection.find(params[:id])
    end

    def set_stage
      @stage = params[:stage] ? params[:stage].to_i : @users_collection.stage
    end

    def set_users_collection
      @users_collection =
        UsersCollection.find_or_create_by(collection_id: @collection.id, user_id: current_user.id) do |uc|
          uc.user = current_user
          uc.collection = @collection
          uc.stage = 1
        end
    end
  end
end

app/controllers/contributors/masterclasses_controller.rb
module Contributors
  class MasterclassesController < ::Contributors::NamespaceController
    def index
      @masterclasses = Masterclass.where(user_id: current_user)
    end

    def show
      @masterclass = Masterclass.find(params[:id])
      respond_to do |format|
        format.html { render :show }
        format.json do
          render json: @masterclass.as_json.merge(
            expert_name: @masterclass.user.full_name,
            expert_image_path: @masterclass.user.bioavatar.avatar_url,
            path: Rails.application.routes.url_helpers.members_masterclass_path(@masterclass),
            image_path: @masterclass.preview_url
          )
        end
      end
    end

    def new
      @masterclass = Masterclass.new
    end

    def create
      @masterclass = Masterclass.new(masterclass_params)

      respond_to do |format|
        if @masterclass.save
          format.html { redirect_to masterclass_path(@masterclass), notice: 'Masterclass added.'}
        else
          format.html { render :new}
        end
      end
    end

    def edit
      @masterclass = Masterclass.find(params[:id])
    end

    def update
      @masterclass = Masterclass.find(params[:id])
      respond_to do |format|
        if @masterclass.update(masterclass_params)
          format.html { redirect_to @masterclass, notice: 'Masterclass updated.' }
        else
          format.html { render :edit }

        end
      end
    end

    def destroy
      @masterclass = Masterclass.find(params[:id])
      @masterclass.destroy
      respond_to do |format|
        format.html { redirect_to masterclass_path, notice: 'The Masterclass was deleted.' }
        format.json { head :no_content }
      end
    end

    private

    def masterclass_params
      params.require(:masterclass).permit(
        :preview,
        :title,
        :text,
        :user_id,
        videos_attributes: [:id, :title, :link,:welcome_video, :position, :_destroy],
        events_attributes: [:id, :title, :link, :_destroy],
        documents_attributes: [:id, :title, :link, :_destroy]
      )
    end

    def set_link
      @masterclass = Masterclass.find(params[:id])
    end
  end
end

app/controllers/contributors/members_club_controller.rb
module Contributors
  class MembersClubController < ::Contributors::NamespaceController
    def workout; end

    def personal_styling
      @collections = Collection.personal_styling
    end

    def personal_development
      @collections = Collection.personal_development
    end

    def workout
      @collections = Collection.workout
    end


    def recipes
      @meal_plans = Post.meal_plan
      @breakfast = Post.breakfast
      @lunch = Post.lunch
      @dinner = Post.dinner
      @snack = Post.snack
      @desert = Post.desert
    end

    def member_orientation; end
  end
end

app/controllers/contributors/namespace_controller.rb
module Contributors
  class NamespaceController < ::ApplicationController
    before_action :authenticate_user!
    before_action :verify_user
    layout 'contributors/application'
    def verify_user
      redirect_to members_root_path if @subscriber
      redirect_to subscriptions_path, notice: 'You are not premium' if @standard
    end
  end
end

app/controllers/contributors/pages_controller.rb
module Contributors
	class PagesController < ::Contributors::NamespaceController
		def index;end

	end
end

app/controllers/contributors/posts_controller.rb
module Contributors
  class PostsController < ::Contributors::NamespaceController
    load_and_authorize_resource
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
      @posts = Post.all
      @posts = @posts.category(params[:category]) if params[:category].present?
    end

    def show
      @post = Post.find(params[:id])
      @comments = @post.comments.all
      @comment = @post.comments.build
    end
    #
    # def new
    #   @post = Post.new
    # end
    #
    # def create
    #   @post = current_user.posts.new(post_params)
    #   if @post.save
    #     redirect_to posts_path, notice: 'Post added.'
    #   else
    #     render :new
    #   end
    # end

    def upvote
      @post = Post.find(params[:id])
      @post.upvote_by current_user
      redirect_back(fallback_location: root_path)
    end


    # def edit; end
    #
    # def update
    #   # @post.assign_attributes(post_params)
    #   # @post.valid?
    #   # @post.errors.full_messages
    #   # @post.inspect
    #   # byebug
    #
    #   if @post.update(post_params)
    #     redirect_to @post, notice: 'Post updated.'
    #   else
    #     #render :edit
    #   end
    # end
    #
    # def destroy
    #   @post.destroy
    #   redirect_to posts_path, notice: 'Your post was deleted.'
    # end

    private

    def post_params
      params.require(:post).permit(:title, :body_text, :image, :post, :post_description, :likes)
    end

    def set_post
      @post = Post.find(params[:id])
    end
  end
end

app/controllers/contributors/users_collections_controller.rb
module Contributors
  class UsersCollectionsController < ::Contributors::NamespaceController
    before_action :set_users_collection
    def update
      @users_collection.update(users_collection_params)
      if users_collection_params[:complete]
        redirect_to members_root_path
      else
        redirect_to(
          members_collection_path(@users_collection.collection_id,
          stage: @users_collection.stage)
        )
      end
    end

    private

    def users_collection_params
      params.require(:users_collection).permit(:stage, :complete)
    end

    def set_users_collection
      @users_collection = UsersCollection.find(params[:id])
    end
  end
end

app/views/layouts/contributors/_header.html.erb
<header class="header">

  <div class="header__inner">

    <%= link_to members_root_path, class: "main-header-title" do %>
      <div class="d-flex flex-column">
        <h1 class="header__logo--signed-in text-center">Health & Style Club</h1>
        <span class="header__logo-small text-center">Contributors Area</span>
      </div>
    <% end %>

    <nav class="header__desktop-nav">
      <ul class="header__desktop-nav-list">
       <li class="header__desktop-nav-item">
          <%= nav_link_to workout_members_members_club_path, class: 'header__desktop-nav-link' do %>
          Workout
          <% end %>
    </li>
        <li class="header__desktop-nav-item">
          <%= nav_link_to recipes_members_members_club_path, class: 'header__desktop-nav-link' do %>
            Recipes
          <% end %>
        </li>
        <li class="header__desktop-nav-item">
          <%= nav_link_to personal_styling_members_members_club_path, class: 'header__desktop-nav-link' do %>
            Personal Styling
          <% end %>
        </li>
        <li class="header__desktop-nav-item">
          <%= nav_link_to personal_development_members_members_club_path, class: 'header__desktop-nav-link' do %>
            Personal Development
          <% end %>
        </li>
        <li class="header__desktop-nav-item">
          <%= nav_link_to members_masterclasses_path, class: 'header__desktop-nav-link' do %>
            Masterclasses
          <% end %>
        </li>
        <li class="header__desktop-nav-item">
          <div class="dropdown">
            <a class="p-0" id="AccountMenu" data-toggle="dropdown">Profile</i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="AccountMenu">
              <%= link_to "View My Profile", "#{members_user_path}/#{current_user.id}", class: "dropdown-item" %>
              <%= link_to "Edit Account", "#{edit_user_registration_path}#account_change", class: "dropdown-item" %>
              <%= link_to "Edit Password", "#{edit_user_registration_path}#password_change", class: "dropdown-item" %>
              <%= link_to "Manage Subscription", subscriptions_path, class: 'dropdown-item' %></a>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </div>
        </li>
      </ul>
    </nav>

    <div class="header__mobile-nav">
      <ul class="mobile-nav__menu">
        <span class="mobile-nav__close"><i class="fa fa-2x fa-times mobile-nav-icon" aria-hidden="true"></i></span>
        <li class="mobile-nav__item"><%= link_to "Home", root_path %></li>
        <li class="mobile-nav__item"><%= link_to "Posts", posts_path %></li>
        <li class="mobile-nav__item"><%= link_to "Members Page", members_user_path %></li>
        <li class="mobile-nav__item"><%= link_to "Contact", new_contact_path %></li>
        <li class="mobile-nav__item"><%= link_to 'Log in', new_user_session_path %></li>
      </ul>
    </div>
  </div>

</header>

app/views/layouts/contributors/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<% if @subscribed
     @background_color = "vip_background"
   end %>
<body class="<%= @background_color %>">
<div class="main-container">
  <div class="main-header-wrapper">
    <%= render 'layouts/contributors/header' %>
  </div>
  <div class="main-body-content">
    <%= yield %>
  </div>

  <div class="main-footer-container">
    <%= render "layouts/footer" %>
  </div>
</div>

</body>
</html>