config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resource :user

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!STANDARD!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  get 'faq' => 'pages#faq'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'termsandconditions' => 'pages#t_c_page'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'our-masterclasses' => 'pages#masterclasses'
  get 'personal-styling' => 'pages#personal_styling'
  get 'become_contributor' => 'pages#become_contributor'
  get 'personal-development' => 'pages#personal_development'
  get 'fitness-and-nutrition' => 'pages#fitness_and_nutrition'

  # resources :photos # TODO: REMOVE RESOURCE
  # resources :contents # TODO: REMOVE RESOURCE
  # resources :comments # TODO: REMOVE RESOURCE
  resources :posts
  resources :attachments
  resources :categories
  resources :contacts, only: %i[new create]
  resources :masterclasses

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!MEMBERS!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :members do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end

  namespace :contributors do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!ADMINS!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admins do
    root to: 'collections#index'
    resources :collections
    resources :masterclasses
    resources :posts
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!CK EDITOR!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  mount Ckeditor::Engine => '/ckeditor'

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!BILLING!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  scope '/subscriptions', :controller => :subscriptions do
    post :webhook_callback
  end

  resources :subscriptions do
    get :new_sub, on: :collection
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!# TODO:
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admin do
    resources :users
    # resources :contents
    # resources :documents
    # resources :events
    resources :masterclasses
    resources :posts

    resources :comments
    # resources :posts_contents
    resources :subscriptions
    resources :categories
    resources :serversettings
    # resources :videos
    root to: 'users#index'
  end
end

app/views/shared/_contributor.html.erb
<div class="d-flex flex-column text-center">
  <div class="mb-3">
    <%= image_tag gravatar_url(contributor.email, 100), style: 'border-radius: 50%' %>
  </div>
  <h4 class="mb-2"><%= contributor.full_name %></h4>
  <p>
    <%= contributor.bio %>
  </p>
</div>

app/views/shared/_current_masterclass.html.erb
<h2 class="mb-5">Our Latest Masterclass</h2>
<div class="container">
  <div class="row ">
    <div class="col-md-1-2 py-4">
      <h4>
        <%= if masterclass
              masterclass.title
            end%>
      </h4>
      <p>
        <%= if masterclass
          masterclass.text
        end%>
      </p>
    </div>
    <div class="col-md-6 align-self-end">
      <%# TODO: UNCOMENT THIS LINE= image_tag masterclass.preview_url, class: 'masterclass-preview-image' %>
    </div>
  </div>
</div>

app/views/shared/_join_now.html.erb
<% if !user_signed_in? %>
  <div class="content-section content-section--dark-grey">
    <div class="content-wrap">
      <h3 class="text-light-pink text-center text-playfair">Ready to become a member?</h3>
      <div class="text-center">
        <%= link_to new_user_registration_path, class: 'btn btn-lg btn-pink mt-3' do %>
          Sign Up Now
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_masterclass_preview.html.erb
<div class="masterclass-small-preview">
  <%= image_tag masterclass.preview_url, class: 'masterclass-small-preview-image shadow' %>
  <div class="masterclass-small-preview-info">
    <h4 class="text-white"><%= masterclass.title  %></h4>
    <small class="text-white"><%= masterclass.user.full_name %></small>
  </div>
</div>

app/views/shared/_model_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <%= model.errors.full_messages.to_sentence %>
  </div>
<% end %>

app/views/shared/_post.html.erb
<div class="post-background d-flex align-items-center no-padding" style="background-image: url(<%# TODO: UNCOMENT THIS LINE= post.image_url %>); background-position: center;">
</div>

<div class="post-blocks">
  <div class="post-content">
      <h5 class="post-index-heading"><%= link_to post.title, post, style:  "color:#990051;" %></h5>
      <h6 class="post-description"><%= sanitize post.post_description, post %></h6>
      <div><p style="font-size:0.75rem; padding-left: 5px;">Posted by <%= post.user.first_name %> <%= post.user.surname%> | <%= post.created_at.strftime("%d %b %y") %></p></div>
    <div style="padding-bottom: 10px; padding-left: 10px;">
      <%# TODO: UNCOMENT THIS LINE= link_to like_post_path(post), method: :put do %>
        <i class="fa fa-heart icon"></i><div class="counter"><%= post.get_upvotes.size %></p></div>
      <%# TODO: UNCOMENT THIS LINE end %>
      </div>
  </div>
</div>