config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resource :user

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!STANDARD!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  get 'faq' => 'pages#faq'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'termsandconditions' => 'pages#t_c_page'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'our-masterclasses' => 'pages#masterclasses'
  get 'personal-styling' => 'pages#personal_styling'
  get 'become_contributor' => 'pages#become_contributor'
  get 'personal-development' => 'pages#personal_development'
  get 'fitness-and-nutrition' => 'pages#fitness_and_nutrition'

  # resources :photos # TODO: REMOVE RESOURCE
  # resources :contents # TODO: REMOVE RESOURCE
  # resources :comments # TODO: REMOVE RESOURCE
  resources :posts
  resources :attachments
  resources :categories
  resources :contacts, only: %i[new create]
  resources :masterclasses

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!MEMBERS!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :members do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end

  namespace :contributors do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!ADMINS!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admins do
    root to: 'collections#index'
    resources :collections
    resources :masterclasses
    resources :posts
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!CK EDITOR!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  mount Ckeditor::Engine => '/ckeditor'

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!BILLING!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  scope '/subscriptions', :controller => :subscriptions do
    post :webhook_callback
  end

  resources :subscriptions do
    get :new_sub, on: :collection
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!# TODO:
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admin do
    resources :users
    # resources :contents
    # resources :documents
    # resources :events
    resources :masterclasses
    resources :posts

    resources :comments
    # resources :posts_contents
    resources :subscriptions
    resources :categories
    resources :serversettings
    # resources :videos
    root to: 'users#index'
  end
end

app/views/layouts/admins/_header.html.erb
<header class="header">

  <div class="header__inner">

    <%= link_to admins_root_path, class: "main-header-title" do %>
      <div class="d-flex flex-column">
        <h1 class="header__logo--signed-in text-center">Health & Style Club</h1>
        <span class="header__logo-small text-center">Admin Area</span>
      </div>
    <% end %>

    <nav class="header__desktop-nav">
      <ul class="header__desktop-nav-list">
        <li class="header__desktop-nav-item">
          <%= nav_link_to admins_collections_path, class: 'header__desktop-nav-link' do %>
            Collections
          <% end %>
        </li>
        <li class="header__desktop-nav-item">
          <%= nav_link_to admins_posts_path, class: 'header__desktop-nav-link' do %>
            Posts
          <% end %>
        </li>
        <li class="header__desktop-nav-item">
          <%= nav_link_to admins_masterclasses_path, class: 'header__desktop-nav-link' do %>
            Masterclasses
          <% end %>
        </li>
        <li class="header__desktop-nav-item">
          <div class="dropdown">
            <a class="p-0" id="AccountMenu" data-toggle="dropdown">Profile</i>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="AccountMenu">
              <%= link_to "View My Profile", "#{members_user_path}/#{current_user.id}", class: "dropdown-item" %>
              <%= link_to "Edit Account", "#{edit_user_registration_path}#account_change", class: "dropdown-item" %>
              <%= link_to "Edit Password", "#{edit_user_registration_path}#password_change", class: "dropdown-item" %>
              <%= link_to "Manage Subscription", subscriptions_path, class: 'dropdown-item' %></a>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </div>
        </li>
      </ul>
    </nav>

<!--    <div class="header__mobile-nav">-->
<!--      <ul class="mobile-nav__menu">-->
<!--        <span class="mobile-nav__close"><i class="fa fa-2x fa-times mobile-nav-icon" aria-hidden="true"></i></span>-->
<!--        <li class="mobile-nav__item"><%#= link_to "Home", root_path %></li>-->
<!--        <li class="mobile-nav__item"><%#= link_to "Posts", posts_path %></li>-->
<!--        <li class="mobile-nav__item"><%#= link_to "Members Page", members_path %></li>-->
<!--        <li class="mobile-nav__item"><%#= link_to "Contact", new_contact_path %></li>-->
<!--        <li class="mobile-nav__item"><%#= link_to 'Log in', new_user_session_path %></li>-->
<!--      </ul>-->
<!--    </div>-->
  </div>

</header>

app/views/layouts/admins/application.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<% if @subscribed
     @background_color = "vip_background"
   end %>
<body class="<%= @background_color %>">
<div class="main-container">
  <div class="main-header-wrapper">
    <%= render 'layouts/admins/header' %>
  </div>

  <div class="main-body-content">
    <%= yield %>
  </div>

  <div class="main-footer-container">
    <%= render "layouts/footer" %>
  </div>
</div>

</body>
</html>