config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resource :user

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!STANDARD!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  get 'faq' => 'pages#faq'
  get 'home' => 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'termsandconditions' => 'pages#t_c_page'
  get 'privacy-policy' => 'pages#privacy_policy'
  get 'our-masterclasses' => 'pages#masterclasses'
  get 'personal-styling' => 'pages#personal_styling'
  get 'become_contributor' => 'pages#become_contributor'
  get 'personal-development' => 'pages#personal_development'
  get 'fitness-and-nutrition' => 'pages#fitness_and_nutrition'

  # resources :photos # TODO: REMOVE RESOURCE
  # resources :contents # TODO: REMOVE RESOURCE
  # resources :comments # TODO: REMOVE RESOURCE
  resources :posts
  resources :attachments
  resources :categories
  resources :contacts, only: %i[new create]
  resources :masterclasses

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!MEMBERS!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :members do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end

  namespace :contributors do
    root to: 'masterclasses#index'
    resource :user
    resources :collections, only: [:show]
    resources :masterclasses, only: %i[index show]
    resources :users_collections, only: [:update]

    # LINKS TO MEMBERS CLUB
    resource :members_club, controller: 'members_club' do
      get :workout
      get 'personal-styling', to: :personal_styling
      get 'personal-development', to: :personal_development
      get :recipes
      get 'member-orientation', to: :member_orientation
    end

    # LIKE AND DISLIKE POSTS
    resources :posts, only: %i[index show] do
      member do
        put 'like', to: 'posts#upvote'
        put 'dislike', to: 'links#downvote'
      end
    end
  end
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!ADMINS!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admins do
    root to: 'collections#index'
    resources :collections
    resources :masterclasses
    resources :posts
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!CK EDITOR!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  mount Ckeditor::Engine => '/ckeditor'

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!BILLING!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  scope '/subscriptions', :controller => :subscriptions do
    post :webhook_callback
  end

  resources :subscriptions do
    get :new_sub, on: :collection
  end

  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!# TODO:
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!TO BE CHANGED!!!!!!!!!!!!!!!
  # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  namespace :admin do
    resources :users
    # resources :contents
    # resources :documents
    # resources :events
    resources :masterclasses
    resources :posts

    resources :comments
    # resources :posts_contents
    resources :subscriptions
    resources :categories
    resources :serversettings
    # resources :videos
    root to: 'users#index'
  end
end

app/controllers/contributors/collections_controller.rb
module Contributors
  class CollectionsController < ::Contributors::NamespaceController
    before_action :set_collection
    before_action :set_users_collection
    before_action :set_stage
    def show; end

    private

    def set_collection
      @collection = Collection.find(params[:id])
    end

    def set_stage
      @stage = params[:stage] ? params[:stage].to_i : @users_collection.stage
    end

    def set_users_collection
      @users_collection =
        UsersCollection.find_or_create_by(collection_id: @collection.id, user_id: current_user.id) do |uc|
          uc.user = current_user
          uc.collection = @collection
          uc.stage = 1
        end
    end
  end
end

app/controllers/contributors/masterclasses_controller.rb
module Contributors
  class MasterclassesController < ::Contributors::NamespaceController
    def index
      @masterclasses = Masterclass.where(user_id: current_user)
    end

    def show
      @masterclass = Masterclass.find(params[:id])
      respond_to do |format|
        format.html { render :show }
        format.json do
          render json: @masterclass.as_json.merge(
            expert_name: @masterclass.user.full_name,
            expert_image_path: @masterclass.user.bioavatar.avatar_url,
            path: Rails.application.routes.url_helpers.members_masterclass_path(@masterclass),
            image_path: @masterclass.preview_url
          )
        end
      end
    end

    def new
      @masterclass = Masterclass.new
    end

    def create
      @masterclass = Masterclass.new(masterclass_params)

      respond_to do |format|
        if @masterclass.save
          format.html { redirect_to masterclass_path(@masterclass), notice: 'Masterclass added.'}
        else
          format.html { render :new}
        end
      end
    end

    def edit
      @masterclass = Masterclass.find(params[:id])
    end

    def update
      @masterclass = Masterclass.find(params[:id])
      respond_to do |format|
        if @masterclass.update(masterclass_params)
          format.html { redirect_to @masterclass, notice: 'Masterclass updated.' }
        else
          format.html { render :edit }

        end
      end
    end

    def destroy
      @masterclass = Masterclass.find(params[:id])
      @masterclass.destroy
      respond_to do |format|
        format.html { redirect_to masterclass_path, notice: 'The Masterclass was deleted.' }
        format.json { head :no_content }
      end
    end

    private

    def masterclass_params
      params.require(:masterclass).permit(
        :preview,
        :title,
        :text,
        :user_id,
        videos_attributes: [:id, :title, :link,:welcome_video, :position, :_destroy],
        events_attributes: [:id, :title, :link, :_destroy],
        documents_attributes: [:id, :title, :link, :_destroy]
      )
    end

    def set_link
      @masterclass = Masterclass.find(params[:id])
    end
  end
end

app/controllers/contributors/members_club_controller.rb
module Contributors
  class MembersClubController < ::Contributors::NamespaceController
    def workout; end

    def personal_styling
      @collections = Collection.personal_styling
    end

    def personal_development
      @collections = Collection.personal_development
    end

    def workout
      @collections = Collection.workout
    end


    def recipes
      @meal_plans = Post.meal_plan
      @breakfast = Post.breakfast
      @lunch = Post.lunch
      @dinner = Post.dinner
      @snack = Post.snack
      @desert = Post.desert
    end

    def member_orientation; end
  end
end

app/controllers/contributors/namespace_controller.rb
module Contributors
  class NamespaceController < ::ApplicationController
    before_action :authenticate_user!
    before_action :verify_user
    layout 'contributors/application'
    def verify_user
      redirect_to members_root_path if @subscriber
      redirect_to subscriptions_path, notice: 'You are not premium' if @standard
    end
  end
end

app/controllers/contributors/pages_controller.rb
module Contributors
	class PagesController < ::Contributors::NamespaceController
		def index;end

	end
end

app/controllers/contributors/posts_controller.rb
module Contributors
  class PostsController < ::Contributors::NamespaceController
    load_and_authorize_resource
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
      @posts = Post.all
      @posts = @posts.category(params[:category]) if params[:category].present?
    end

    def show
      @post = Post.find(params[:id])
      @comments = @post.comments.all
      @comment = @post.comments.build
    end
    #
    # def new
    #   @post = Post.new
    # end
    #
    # def create
    #   @post = current_user.posts.new(post_params)
    #   if @post.save
    #     redirect_to posts_path, notice: 'Post added.'
    #   else
    #     render :new
    #   end
    # end

    def upvote
      @post = Post.find(params[:id])
      @post.upvote_by current_user
      redirect_back(fallback_location: root_path)
    end


    # def edit; end
    #
    # def update
    #   # @post.assign_attributes(post_params)
    #   # @post.valid?
    #   # @post.errors.full_messages
    #   # @post.inspect
    #   # byebug
    #
    #   if @post.update(post_params)
    #     redirect_to @post, notice: 'Post updated.'
    #   else
    #     #render :edit
    #   end
    # end
    #
    # def destroy
    #   @post.destroy
    #   redirect_to posts_path, notice: 'Your post was deleted.'
    # end

    private

    def post_params
      params.require(:post).permit(:title, :body_text, :image, :post, :post_description, :likes)
    end

    def set_post
      @post = Post.find(params[:id])
    end
  end
end

app/controllers/contributors/users_collections_controller.rb
module Contributors
  class UsersCollectionsController < ::Contributors::NamespaceController
    before_action :set_users_collection
    def update
      @users_collection.update(users_collection_params)
      if users_collection_params[:complete]
        redirect_to members_root_path
      else
        redirect_to(
          members_collection_path(@users_collection.collection_id,
          stage: @users_collection.stage)
        )
      end
    end

    private

    def users_collection_params
      params.require(:users_collection).permit(:stage, :complete)
    end

    def set_users_collection
      @users_collection = UsersCollection.find(params[:id])
    end
  end
end

app/controllers/members/members_club_controller.rb
module Members
  class MembersClubController < ::Members::NamespaceController
    def workout; end

    def personal_styling
      @collections = Collection.personal_styling
    end

    def personal_development
      @collections = Collection.personal_development
    end

    def workout
      @collections = Collection.workout
    end


    def recipes
      @meal_plans = Post.meal_plan
      @breakfast = Post.breakfast
      @lunch = Post.lunch
      @dinner = Post.dinner
      @snack = Post.snack
      @desert = Post.desert
    end

    def member_orientation; end
  end
end

app/views/contributors/members_club/_collections.html.erb
<% if collections.present? %>

  <% collections.each do |collection| %>

    <div class="col-12 col-sm-6 col-md-4">
      <div class="card h-100">
        <%= link_to members_collection_path(collection) do %>
          <header class="card-header background-dark-grey text-center">
            <div class="d-flex flex-column justify-content-center align-items-center">
              <h5 class="text-light-pink mb-0"><%= collection.name %></h5>
              <span class="mt-2">
                <% collection.videos.each_with_index do |video, index| %>
                  <% stage = current_user.users_collections.where(collection: collection).first&.stage || 0 %>
                  <% if stage > index + 1 %>
                    <i class="fa fa-2x fa-fw fa-check-circle-o text-light-pink" aria-hidden="true"></i>
                  <% else %>
                    <i class="fa fa-2x fa-fw fa-circle-o text-light-pink" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </span>
            </div>
          </header>
          <% if collection.preview.present? %>
            <%= image_tag collection.preview_url, class: 'card-img' %>
          <% end %>
          <div class="card-body">
            <p class="card-text">
              <%= collection.description %>
            </p>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

<% else %>
  <div class="col-12 text-center">
    <p>There are currently no collections, please check back later.</p>
  </div>

<% end %>

app/views/contributors/members_club/personal_development.html.erb
<div class="content-section">
  <div class="content-wrap">
    <h2 class="text-center mb-4">Personal Development</h2>

    <div class="container">
      <div class="row">

        <%= render 'collections', collections: @collections %>

      </div>
    </div>
  </div>
</div>

app/views/contributors/members_club/personal_styling.html.erb
<div class="content-section">
  <div class="content-wrap">
    <h2 class="text-center mb-4">Personal Styling</h2>

    <div class="container">
      <div class="row">

        <%= render 'collections', collections: @collections %>

      </div>
    </div>
  </div>
</div>

app/views/contributors/members_club/recipes.html.erb
<div class="content-section">
  <div class="content-wrap">

    <h2 class="text-center mt-2">Recipes</h2>

<!--    <h4 class="text-center mt-5">Meal Plans</h4>-->
<!--    <div class="row justify-content-center">-->

      <%# @meal_plans.each do |r| %>
        <%#= link_to members_post_path(r.id) do %>
<!--          <div class="card margin-sides margin-top-bottom" style="width: 14rem;">-->
            <%# if r.image? %>
              <%#= image_tag r.image.post_image_thumb %>
            <%# else %>
<!--              <img class="card-img-top" src="https://www.oxygenmag.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTQ1MzQ3MzE0ODg4MDI1ODcz/image-placeholder-title.jpg" alt="Card image cap">-->
            <%# end %>
<!--            <div class="card-body">-->
<!--              <h5 class="card-title"><strong><%#= r.title %></strong></h5>-->
<!--              <p class="card-text"><%#= r.post_description %></p>-->
<!--            </div>-->
<!--          </div>-->
        <%# end %>
      <%# end %>

<!--    </div>-->

    <h4 class="text-center mt-5">Breakfast</h4>
    <div class="row justify-content-center">

      <% @breakfast.each do |r| %>
        <%= link_to members_post_path(r.id) do %>
          <div class="card margin-sides margin-top-bottom" style="width: 14rem;">
            <% if r.image? %>
              <%= image_tag r.image.post_image_thumb%>
              <% else %>
            <img class="card-img-top" src="https://www.oxygenmag.com/.image/ar_16:9%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cg_faces:center%2Cq_auto:good%2Cw_620/MTQ1MzQ3MzE0ODg4MDI1ODcz/image-placeholder-title.jpg" alt="Card image cap">
            <% end %>
              <div class="card-body">
              <h5 class="card-title"><strong><%= r.title%></strong></h5>
              <p class="card-text"><%= r.post_description%></p>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>

    <h4 class="text-center mt-5">Lunch</h4>
      <div class="row justify-content-center">
        <% @lunch.each do |r|%>
          <%= link_to members_post_path(r.id) do %>
          <div class="card margin-top-bottom margin-sides" style="width: 14rem;">
            <% if r.image? %>
              <%= image_tag r.image.post_image_thumb%>
              <% else %>
            <img class="card-img-top" src="http://joesbarfullerton.com/wp-content/uploads/2017/11/burger.jpg" alt="Card image cap">
            <% end %>
              <div class="card-body">
              <h5 class="card-title"><strong><%= r.title%></strong></h5>
              <p class="card-text"><%= r.post_description%></p>
            </div>
          </div>
        <%end
        end%>
      </div>

    <h4 class="text-center mt-5">Dinner</h4>
      <div class="row justify-content-center">
        <% @dinner.each do |r|%>
          <%= link_to members_post_path(r.id) do %>
          <div class="card margin-top-bottom margin-sides" style="width: 14rem;">
            <% if r.image? %>
              <%= image_tag r.image.post_image_thumb%>
              <% else %>
            <img class="card-img-top" src="http://www.435mag.com/images/cache/cache_5/cache_7/cache_0/DateNight_TN-56107075.jpeg?ver=1517968202&aspectratio=1.5009380863039" alt="Card image cap">
            <% end %>
              <div class="card-body">
              <h5 class="card-title"><strong><%= r.title%></strong></h5>
              <p class="card-text"><%= r.post_description%></p>
            </div>
          </div>
        <%end
          end%>
      </div>

    <h4 class="text-center mt-5">Snack</h4>
      <div class="row justify-content-center">
        <% @snack.each do |r|%>
          <%= link_to members_post_path(r.id) do %>
          <div class="card margin-top-bottom margin-sides" style="width: 14rem;">
            <% if r.image? %>
              <%= image_tag r.image.post_image_thumb%>
              <% else %>
            <img class="card-img-top" src="https://www.madewithnestle.ca/sites/default/files/styles/recipe_main_image/public/rolo_peanut_butter_sweet_and_salty_trail_mix_0.jpg" alt="Card image cap">
            <% end %>
              <div class="card-body">
              <h5 class="card-title"><strong><%= r.title%></strong></h5>
              <p class="card-text"><%= r.post_description%></p>
            </div>
          </div>
        <%end
        end%>
      </div>

    <h4 class="text-center mt-5">Desert</h4>
      <div class="row justify-content-center">
        <% @desert.each do |r| %>
          <%= link_to members_post_path(r.id) do %>
          <div class="card margin-top-bottom margin-sides" style="width: 14rem;">
            <% if r.image? %>
              <%= image_tag r.image.post_image_thumb%>
              <% else %>
            <img class="card-img-top" src="https://casamia.co.za/wp-content/uploads/2017/09/chocolate-fudge-cake-with-truffles-.jpg" alt="Card image cap">
            <% end %>
              <div class="card-body">
              <h5 class="card-title"><strong><%= r.title%></strong></h5>
              <p class="card-text"><%= r.post_description%></p>
            </div>
          </div>
        <% end
        end%>
      </div>
  </div>
</div>

app/views/contributors/members_club/workout.html.erb
<div class="content-section">
  <div class="content-wrap">
    <h2 class="text-center mb-4">Personal Development</h2>

    <div class="container">
      <div class="row">

        <%= render 'collections', collections: @collections %>

      </div>
    </div>
  </div>
</div>